# Generated by Django 4.0.6 on 2022-07-28 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField(blank=True, default=0.0, null=True)),
                ('obs', models.TextField(blank=True, verbose_name='observation')),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=30, verbose_name='ClassRoom Name')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=120, verbose_name='Coures Name')),
                ('coefficiant', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('gender', models.CharField(max_length=20, verbose_name='Gender')),
                ('email', models.CharField(max_length=120, verbose_name='Email Address')),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('classRoom', models.ManyToManyField(to='student_app.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('gender', models.CharField(max_length=20, verbose_name='Gender')),
                ('email', models.CharField(max_length=120, verbose_name='Email Address')),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('classRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.classroom')),
                ('courses', models.ManyToManyField(through='student_app.Bulletin', to='student_app.coures')),
            ],
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField(blank=True, null=True)),
                ('montant', models.IntegerField(blank=True, null=True)),
                ('nom_etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.student')),
            ],
        ),
        migrations.AddField(
            model_name='coures',
            name='teachers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.teacher'),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='etudiants',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.student'),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='matieres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.coures'),
        ),
    ]
